# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/*

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs: 
      - job: buildJob
        steps:
          - script: echo Build job
            displayName: Print Information
          - script: 
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
            displayName: 'Run a multi-line script'
          - script: 
              npm install @salesforce/cli --global
  - stage: deploy
    jobs:
      - job: deployJob
        steps: 
          - script: echo build job
            displayName: 'Run a build job'
  - stage: test
    jobs:
      - job: TestJob
        steps:
          - script: echo test job
            displayName: 'Run a Test Job'

