# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
      - job: buildjob
        steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'
          - script: echo Add other tasks to build, test, and deploy your project.
                    echo See https://aka.ms/yaml
            displayName: 'Run a multi-line script'
          - script: npm install @salesforce/cli --global
                    sf --version
          - checkout: self
            fetchDepth: 0

  - stage: deploy
    jobs:
      - job: deployjob
        steps:
          - script: echo Hello, World
            displayName: 'Run one-line script'

  - stage: test
    jobs: 
      - job: testjob
        steps:
          - script: echo hello
            displayName: 'Run one-line script'


